"""empty message

Revision ID: b7ae9d7e7304
Revises: 
Create Date: 2022-01-30 16:59:25.797743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ae9d7e7304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stonk', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('stonk', 'stonk',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('stonk', 'ticker',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_stonk_ticker'), 'stonk', ['ticker'], unique=True)
    op.create_unique_constraint(None, 'stonk', ['stonk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stonk', type_='unique')
    op.drop_index(op.f('ix_stonk_ticker'), table_name='stonk')
    op.alter_column('stonk', 'ticker',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('stonk', 'stonk',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('stonk', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
