version: "3.7"
services:
  app:
    build: ./app
    container_name: "stonk_scraper"
    command: python stonk-scraper.py
    ports:
      - "5000:5000"
    env_file: variables.env
  database:
    container_name: postgres
    image: postgres:latest
    env_file: variables.env
    ports:
      - "5432:5432"